### ISSUE TITLE
Plugin not working with mkdocs 1.0.x

### ISSUE THREAD

**Issue by dduportal** [rosscdh/mkdocs-markdownextradata-plugin#3]
Hello dear maintainer,

thanks for this cool plugin!

Just installed the version `0.0.5`, with mkdocs `1.0.4` with success,
and ran into this error:

```
ERROR   -  Config value: 'markdown_extensions'. Error: Failed to initiate extension 'markdownextradata': module 'markdownextradata' has no attribute 'makeExtension'
```

Reproduction:

* `Dockerfile`:
```
FROM alpine:3.8

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin

COPY requirements.txt /mkdocs/
WORKDIR /mkdocs
VOLUME /mkdocs

RUN apk --no-cache --no-progress add py3-pip \
  && pip3 install --user -r requirements.txt
```

* `requirements.txt`:

```
mkdocs==1.0.4
pymdown-extensions==5.0
mkdocs-bootswatch==1.0
mkdocs-material==3.0.4
mkdocs-markdownextradata-plugin==0.0.5
```

* `mkdocs.yml`:

```
site_name: Foo
site_description: Foo
site_author: Foo
site_url: https://foo.com
dev_addr: 0.0.0.0:8000

docs_dir: 'content'

theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  favicon: assets/img/favicon.ico
  logo: assets/img/foo.png
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'blue'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; foo"

markdown_extensions:
  - admonition
  - markdownextradata
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true

extra:
  fooVersion: 1.0.0

# Page tree
nav:
  - 'Welcome': 'index.md'
```

**Comment by rosscdh** [comment]
Hi, thanks for the info. I'll try replicate and fix the issue this weekend.

**Comment by rosscdh** [comment]
Ok did a little initial investigation. 2 things

1. Thanks for the great report, really well written and helped with resolution from text
2. the problem is

you have:

```
markdown_extensions:
  - admonition
  - markdownextradata
....
```

it should be

```
plugins:
  - markdownextradata

markdown_extensions:
  - admonition
  - pymdownx.details
....
```

Remember its a "plugin" not an extension ;)

**Comment by rosscdh** [comment]
Best of luck with your project and thanks again for the report!

**Comment by rosscdh** [comment]
Great to hear absolutely no problem! Good luck with the project and drop a
line if tethers is anything else
